baseURL = "https://ios.witbit.io"
# relativeURLs = true
languageCode = "en-us"
title = "iOS Wit Bit"
theme = "hyde-xx"

paginate = 10

[author]
    name = "iOS Wit Bit"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    # defaultDescription = "Your default page description"
    # defaultKeywords = "your,default,page,keywords"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = true

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-00"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "atelier-forest.light"

    # Optional additional custom CSS file URL, will override other styles.
    # customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    # tagline = "Your favourite quote or soundbite."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Home"

    # Metadata used to drive integrations.
    # googleAnalytics = "Your Google Analytics tracking code"
    # gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/dmial"
    # bitbucket = ""
    # stackOverflow = ""
    # linkedin = ""
    # googleplus = ""
    # facebook = ""
    # twitter = ""
    # youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
    # flattr = ""  # populate with your flattr uid
