baseURL = "https://witbit.io"
languageCode = "en-EN"

theme = "hyde-wb"

paginate = 10
paginatePath = "page"

copyright = "(c) 2018 Dmitriy Alexeev"

disqusShortname = "witbitsite"

[author]
    name = "Dmitriy Alexeev"
    email = "dima@alexeev.biz"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"
    
[taxonomies]
    tag = "tags"

[params]
    
    # You can use markdown here.
    brand = "WIT BIT"
    topline = "bits of knowledge: iOS software development and more"
    footline = "Do stuff with ❤️"
    
    sidebar = "right" # false, true, "left", "right"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Select a syntax highight for highlight.js
    # Leave unset to fall back to default hugo highlighter instead of highlight.js
    highlight = "github"

    # Google Analytics.
    # googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "dmial" # Your Github profile ID
    facebook = "dima.alexeev" # Your Facebook profile ID
    telegram = "witbitio"
    linkedin = "dima-alexeev"
    rss = true
    # bitbucket = "" # Your Bitbucket profile ID
    # googleplus = "" # Your Google+ profile ID
    # twitter = "" # Your Twitter profile ID
    # youtube = ""  # Your Youtube channel ID
    # flattr = ""  # populate with your flattr uid
    # flickr = "" # Your Flickr profile ID
    # vimeo = "" # Your Vimeo profile ID
    
    readingMeasures = false # "Read in about X min · (Y Words)" 

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
